### ISSUE TITLE
Dispute contract design

### ISSUE THREAD

**Issue by mzxyz** [subquery/network-contracts#107]
## Dispute types:

* POI dispute
* Query dispute

## Dispute contract

Contract name: `DisputeManager`

### Types 

```sol
enum DisputeType {
	POIDispute,
        QueryDispute
}

enum DisputeState {
	Accept,
        Reject,
        Draw
}

struct Dispute {
        uint256 disputeId;
	byte32 metadata;          // encoded attestation from indexer
        uint256 staking;             // indexer staking amount	
        bytes32 deploymentId; // project deployment id
	address indexer;            // indexer address
	address reporter;          // reporter address
	DisputeType type;         // dispute type
        uint256 endEra;            // end era number
        DisputeState state;       // dispute state
}

struct validation {
        byte32 metadata;          // encoded attestation from validator
        uint256 disputeId;         // dispute id
        address validator;          // validator address
        uint256 staking;            // validator staking amount
        bool result;                    // result for validation(accept or reject)
}
```

### States

```sol
uint256 public defultSlashRate;
uint256 public fishermanRate;
uint256 public minimumDeposit;
uint256 public nextDisputeId;
// indexer address -> dispute ids
mapping(address => uint256[]) disputeIdsByIndexer;
// fisherman address -> dispute ids
mapping(address => uint256[]) disputeIdsByReporter;
// id -> Dispute
mapping(uint256 => Dispute) disputes;
// dispute id -> validations
mapping(uint256 => validation[]) validations;
// validator address -> dispute id -> validation
mapping(address => uint256 => validation) validationByValidator;
// reward by disputeId
mapping(uint256 => uint256) rewards;
```

### Functions

```sol
function createPoiDispute(uint256 deposit, bytes32 metadata) external {
	// 1. Ensure that caller's deposit and transfer the deposit from caller to this contract
        // 2. parse metadata 
        // 3. create new dispute instance
	// 4. update `disputeIdsByIndexer`, `disputeIdsByReporter` and `disputes`
	// 5. nextDisputeId++
	// 6. emit event
}

function createQueryDispute(uint256 deposit, bytes32 metadata) external {
	// 1. Ensure that caller's deposit and transfer the deposit from caller to this contract
        // 2. parse metadata 
	// 2. create new dispute instance
	// 3. update `disputeIdsByIndexer`, `disputeIdsByReporter` and `disputes`
	// 4. nextDisputeId++
	// 5. emit event
}

function joinValidation(uint256 id, uint256 deposit, bool result, bytes32 metadata) external {
	// 1. Ensure that caller's deposit and transfer the deposit from caller to this contract
        // 2. parse metadata
        // 3. create  validation instance
	// 2. update `disputeIdsByIndexer`, `disputeIdsByReporter`, `validation`, `validationByValidator`,  and `disputes`
	// 4. emit event
}

function updateValidation(uint256 id, bool result, bytes32 metadata) external {
       // update  validation instance
}

// anyone can call this function to finalize a dispute
function finalizeDispute(uint256 disputeId) external {
        // 1. check dispute expire
        // 2. get result from validations
        // 3. according to result to slash
        // if accept call `_slashIndexer(  uint256 disputeId  )`
        // if reject call `_slashFisherman(  uint256 disputeId  )`
        // if draw return fisherman's deposit
        // 4. update `disputes`
        // 5. emit event
}

function extendDispute(uint256 disputeId, uint256 expireEra) external onlyOwner {
        // 1. check new expireEra
        // 2. check dispute status
        // 3. update `disputes`
}

// Make the staking contract slash the indexer 
// Give the fisherman and validators a reward equal to the fishermanRewardPercentage of slashed amount
function _slashIndexer( uint256 disputeId ) private {
      // 1. Get slashable amount for indexer
      // 2. Calculate the slash amount as the rewards for fisherman and validator
      // 3. call slash from staking to transfer slashed token to this contract
      staking.slash(_indexer, slashAmount);
      // 4. transfer fisherman's rewards to fisherman
      // 5. update `rewards` and wait validators to claim
}

function _slashFisherman( uint256 disputeId ) private {
       // 1. Get slashable amount for fisherman
       // 2. Calculate the slash amount 
       // 3. transfer indexer's rewards to indexer
       // 4. update `rewards` and wait validators to claim
}

function claimReward(uint256 disputeId) external {
      // 1. check caller is valid to claim rewards
      // 2. calculate the amonut to claim
      // 3. transfer token to caller
}

// a function to check an indexer has dispute
function hasDispute(address indexer) returns(bool) external;

function disputeCountByIndexer(address _indexer) external view returns (uint256);
function disputeCountByReporter(address _reporter) external view returns (uint256);
```

### Functions
```sol
function slash(address _indexer, uint256 slashAmount) external {
       // 1. check caller is disputeManager
       // 2. check indexer's staking is enough 
       // 3. transfer slashAmount to disputeManager
       // 4. update indexer's staking amount
}

function stake() {
       // check `hasDispute` from disputeManager
       ........
}

function unstake() {
       // check `hasDispute` from disputeManager
       ........
}

```

**Comment by HZHAIX** [comment]
![Dispute System (1)](https://user-images.githubusercontent.com/8177474/201550247-79d78ea1-458d-4e4f-b656-9ffabf2283e3.png)

**Comment by Jianzhuo** [comment]
![Dispute System (1)](https://user-images.githubusercontent.com/67722296/203445358-34621f94-9c0f-4121-800f-2de261c9c852.png)

**Comment by HZHAIX** [comment]
Cases Discussion:

1. Do we need different `minumDeposit` for `fisherman` and `validator`,  and `slash rate` for indexer and `failed validators` 

2. Do we only slash `indexer` or slash `failed validators` as well

3. Allocate rewards to fisherman and validator
- Save rewards
- Or basing on their deposit amount / total deposit

**Comment by mzxyz** [comment]
## Metadata in Creating Dispute

- How to encode and decode the metadata
encode method
```
function encodeMetadata(Receipt memory _receipt) public view override returns (bytes32) {
  return
      keccak256(
          abi.encodePacked(
              "\x19\x01", // EIP-191 encoding pad, EIP-712 version 1
              DOMAIN_SEPARATOR,
              keccak256(
                  abi.encode(
                      RECEIPT_TYPE_HASH,
                      _receipt.requestCID,
                      _receipt.responseCID,
                      _receipt.deploymentId
                  ) // EIP 712-encoded message hash
              )
          )
      );
}
```
decode method
```
uint256 private constant RECEIPT_SIZE_BYTES = 96;
uint256 private constant SIG_R_LENGTH = 32;
uint256 private constant SIG_S_LENGTH = 32;
uint256 private constant SIG_V_LENGTH = 1;
uint256 private constant SIG_R_OFFSET = RECEIPT_SIZE_BYTES;
uint256 private constant SIG_S_OFFSET = RECEIPT_SIZE_BYTES + SIG_R_LENGTH;
uint256 private constant SIG_V_OFFSET = RECEIPT_SIZE_BYTES + SIG_R_LENGTH + SIG_S_LENGTH;

// Parse a uint8 from `_bytes` starting at offset `_start`.
function _toUint8(bytes memory _bytes, uint256 _start) private pure returns (uint8) {
    require(_bytes.length >= (_start + UINT8_BYTE_LENGTH), "Bytes: out of bounds");
    uint8 tempUint;

    assembly {
        tempUint := mload(add(add(_bytes, 0x1), _start))
     }

    return tempUint;
}

// Parse a bytes32 from `_bytes` starting at offset `_start`.
function _toBytes32(bytes memory _bytes, uint256 _start) private pure returns (bytes32) {
    require(_bytes.length >= (_start + BYTES32_BYTE_LENGTH), "Bytes: out of bounds");
    bytes32 tempBytes32;

    assembly {
        tempBytes32 := mload(add(add(_bytes, 0x20), _start))
    }

    return tempBytes32;
}
```

```
// Decode receipt
(bytes32 requestCID, bytes32 responseCID, bytes32 deploymentId) = abi.decode(
    _data,
    (bytes32, bytes32, bytes32)
);

// Decode signature
// Signature is expected to be in the order defined in the Attestation struct
bytes32 r = _toBytes32(_data, SIG_R_OFFSET);
bytes32 s = _toBytes32(_data, SIG_S_OFFSET);
uint8 v = _toUint8(_data, SIG_V_OFFSET);
```
- What includes in the metadata
Query metadata includes requestCID, responseCID, deploymentId and signature
indexer sign the response message and the output is r,s,v by ECDSA  algorithm 
```
struct QueryMetadata {
    bytes32 requestCID;
    bytes32 responseCID;
    bytes32 deploymentId;
    bytes32 r;
    bytes32 s;
    uint8 v;
}
```
POI metadata includes block height, block hash and signature
Indexers periodic sign and report their POI and the signature(r,s,v) is the output of ECDSA  algorithm
```
struct POIMetadata {
    uint256 blockHeight;
    uint256 blockHash;
    bytes32 r;
    bytes32 s;
    uint8 v;
}
```

**Comment by Jianzhuo** [comment]
## Cases Discussion:
- During the dispute we have multiple role involved in, `Indexer`, `fisherman` and `validator`. It seems to apply the same `minumDeposit` and `slashRate` to all these roles are not fair, we need to discuss the different `minumDeposit` and `slashRate` for different roles.
- Since `validators` are validate and submit their results to a dispute which could be accept or reject. Validator can submit wrong result to affect the final result of the dispute. So we need discuss if the dispute accepted in final result, we also slash these validators who submit the reject result, vice versa.
- We slash the indexer or fisherman rewards to validators, and we could also provide some rewards from the treasure to excitate and support validators, we need to discuss the composition and distribution of Rewards.
where does the reward come from -- slashed SQT and subquery treasure support?
how to allocate rewards -- save rewards or basing on validators' deposit amount / total deposit?
- Before the dispute finalized, do we need to allow validator withdraw the validation, or decrease the deposit, we may charge some fees for these requests.

**Comment by Jianzhuo** [comment]
Cases Discussion:
- During the dispute we have multiple role involved in, `Indexer`, `fisherman` and `validator`. It seems to apply the same `minumDeposit` and `slashRate` to all these roles are not fair, we need to discuss the different `minumDeposit` and `slashRate` for different roles.
- Since `validators` are validate and submit their results to a dispute which could be accept or reject. Validator can submit wrong result to affect the final result of the dispute. So we need discuss if the dispute accepted in final result, we also slash these validators who submit the reject result, vice versa.
- We slash the indexer or fisherman rewards to validators, and we could also provide some rewards from the treasure to excitate and support validators, we need to discuss the composition and distribution of Rewards.
where does the reward come from -- slashed SQT and subquery treasure support?
how to allocate rewards -- save rewards or basing on validators' deposit amount / total deposit?
- Before the dispute finalized, do we need to allow validator withdraw the validation, or decrease the deposit, we may charge some fees for these requests.

**Comment by Jianzhuo** [comment]
## How dose validators validate 
### POI Dispute
Indexers will periodic report their POI include the message(block height, block hash) and their signature(r,s,v).
Fisherman create the POI dispute with the encoded metadata include the message(block height, block hash) and indexer's signature(r,s,v)
Validators can take the message and signature to recover the indexer's address to verify.
```
struct POIMetadata {
    uint256 blockHeight;
    uint256 blockHash;
    bytes32 r;
    bytes32 s;
    uint8 v;
}
```
### Query Dispute
Indexer need to sign the response message when their response consumers(r,s,v).
Fisherman create the query dispute with the encoded metadata include requestCID, responseCID, deploymentId and indexer's signature(r,s,v).
Validators first need to take the response message from responseCID and signature to recover the indexer's address to verify the response message is sent from indexer. Validators also need to verify the accuracy of indexer's response by indexing the deployment locally.
