### ISSUE TITLE
Expose creator at OpenStateChannel event

### ISSUE THREAD

**Issue by heyacherry** [subquery/network-contracts#108]
Record the `real consumer`  when the user open the state channel. 

Current the stateChannel at subql, the consumers field can be either contract address or consumer account. 
It would be good to have a field for recording the real consumer/channel creator.

**Comment by nz-neooo** [comment]
We have two ways if want this result in subql:
1. In the subql mapping, decode the callback data with consumer host style, and then can get the real consumer. (Not common)
2. In the contract, after handle open, and call the real consumer with channel id from `IConsumer`, and add it to open event. (Add IConsumer interface)

**Comment by heyacherry** [comment]
As the filed of `consumer` exposed by `event ChannelOpen` can be either `consumer` or `contract address`, so proposal to make changes on consumer field naming: `event ChannelOpen(..., ...,  address consumer,` --> `event ChannelOpen(..., ...,  address creator,`

**Comment by mzxyz** [comment]
@Jianzhuo don't this change any more
