### ISSUE TITLE
Create contract on Acala EVM+ requires more Transaction Fee than other EVMs

### ISSUE THREAD

**Issue by Jianzhuo** [subquery/network-contracts#14]
In our case, Whenever the consumer and the Indexer accept the offer, we will create a `ClosedServiceAgreement` contract for them within `establishServiceAgreement` of `ServiceAgreementRegistry` contract.

But on Acala EVM+ the transaction fee cost of creating the contract is very large. This makes our users pay a lot of transaction fees when `acceptPurchaseOffer`，`acceptPlan`，`renewAgreement`.

After testing on Acala Mandala TC7, the transaction fee of creating a `closedserviceagreement` alone exceeds 1 ACA when users perform these operations.

**Comment by HZHAIX** [comment]
**Proposals:**

- [ ] Migrate serviceAgreement contract to struct state
- [ ] Migrate related functions
- [ ] Whether main these states and functions in serviceAgreementRegistry or separate contract (ClosedServiceAgreement)
- [ ] The interaction between serviceAgreementRegistry and ClosedServiceAgreement
- [ ] Open market potential problem
