### ISSUE TITLE
Support `maintenance mode` for network

### ISSUE THREAD

**Issue by HZHAIX** [subquery/network-contracts#3]
## Context

We need the network can switch to `maintenance mode` once There has emergency accident happens in the future. Under the maintenance mode, the era will be paused and all the other operations should be forbidden.

## Requirements

- [ ] Support pause era increment in EraManager contract. Era paused as default when deploy the contract, need manually change the status.
- [ ] Add tests to check all the state and actions under maintenance mode

**Comment by Jianzhuo** [comment]
In the maintenance mode, we wish any token transfer related functions need to be forbidden in the network, I list the following function to discuss:

```
bool public maintenance;

if(maintenance){
    require(owner() == _msgSender(), "Network is in maintenance mode");
}
```
### Airdropper
claimAirdrop()
batchClaimAirdrop()
settleEndedRound()

### EraManager
startNewEra()
safeUpdateAndGetEra()

### IndexerRegistry
registerIndexer()
unregisterIndexer()

### ConsumerHost
approve()
disapprove()
deposit()
withdraw()

### PermissionedExchange
trade()
settleExpiredOrder()
cancelOrder()

### PlanManager
createPlan()
removePlan()
acceptPlan()

### PurchaseOfferMarket
createPurchaseOffer()
cancelPurchaseOffer()
acceptPurchaseOffer()

### RewardsDistributer
collectAndDistributeRewards()
claimFrom()

### StakingManager
stake()
unstake()
delegate()
undelegate()
redelegate()
widthdraw()
cancelUnbonding()

Also there are problems occurs by Era paused in maintenance mode need to discuss:
1. InflationController / mintInflatedTokens() Although we paused the era in maintenance mode, the SQT still in inflation.
2. In maintenance mode is indexer also stop query service, this will effects rewards and QueryRegistry.
3. Is necessary to  forbidden user config their accounts in maintenance mode such as addController, setCommissionRate.
