### ISSUE TITLE
Subquery network Governance 

### ISSUE THREAD

**Issue by Jianzhuo** [subquery/network-contracts#5]
When The Subquery network launches, it will be governed by The Subquery Community and Subquery Council. 

The below chart provides a practical overview of how a proposal moves through the Network Governance process:

![My First Board](https://user-images.githubusercontent.com/67722296/172766903-85db0304-e9b7-462e-bab9-d275ea32412c.jpg)

## Subquery Council
The Subquery Council will be a 6-of-10 multisig that balances the interests of five core stakeholder groups: Indexers, active token holders, the initial team, users(Consumers and Delegators) and technical domain experts.
After the proposal is put forward by the community and voted by the community, Subquery Council Multisig(6-of-10 required) to execute the implementation. 
In addition, the each council member will be authorised to following operations:
- Emergency network Operations: pause or stop the network in the event of an emergency, in which case restarting the protocol with a bug fix.
- Reject sign to execution execute the implementation

## Governance Functions
There are three main buckets of Governance Functions:
1. Network Operations
Issue network upgrades, network parameterisation.
2. Ecosystem Funding
Issue grants from the treasury to support The Subquery's ecosystem.
3. Foundation Management

## Subquery Council Multisig
Given our requirements, we decided to integrate a Multi-Signature wallet for Subquery Council. We require 6-of-10 council members signed for every operation.

## Voting System
[Snapshot](https://docs.snapshot.org/) is a decentralized voting system. It provides flexibility on how voting power is calculated for a vote. Snapshot supports various voting types to cater to the needs of organizations. Creating proposals and voting on Snapshot is user-friendly and does not cost gas as the process is performed off-chain.
We use the "erc20 balance of" strategy  which vote based on the number of tokens held in the user account in a certain height of the blockchain.
### sSQT token
We added sSQT token for voting with SQT token. When the user stake SQT token, the user will get the same number of sSQT. When the user unstake, the user will be required to provide the same number of sSQT. In this way, the part of SQT staked by users can also be used for voting.
### Proposal struct
After the voting is completed, we will submit the proposal contents and voting results and permanently save them on the blockchain.
```
contract SubqueryGovernance {
   
     ......

    /**
     * Create a on chain proposal that links to a Subquery Governance Proposal 
     * @param _proposalId Proposal identifier. This is an IPFS hash to the content of the GGP
     * @param _votes An IPFS hash of the collection of signatures for each vote of the GGP.
     * @param _metadata A bytes32 field to attach metadata to the proposal if needed
     * @param _resolution Resolution choice, either Accepted or Rejected
     */
    function createProposal(
        bytes32 _proposalId,
        bytes32 _votes,
        bytes32 _metadata,
        ProposalResolution _resolution
    ) external {
         ......
    }

    /**
     * Updates an existing on chain proposal that links to a Subquery Governance Proposal 
     * @param _proposalId Proposal identifier. This is an IPFS hash to the content of the GGP
     * @param _votes An IPFS hash of the collection of signatures for each vote of the GGP.
     * @param _metadata A bytes32 field to attach metadata to the proposal if needed
     * @param _resolution Resolution choice, either Accepted or Rejected
     */
    function updateProposal(
        bytes32 _proposalId,
        bytes32 _votes,
        bytes32 _metadata,
        ProposalResolution _resolution
    ) external {
        ......
    }
}
```
```
struct Proposal {
        bytes32 votes; // IPFS hash of signed votes
        bytes32 metadata; // Additional info that can be linked
        ProposalResolution resolution;
 }
```
```
enum ProposalResolution {
        Null,
        Accepted,
        Rejected
}
```

**Comment by Jianzhuo** [comment]
## Voting Token
There is another approach to calculate the user's voting power, instead of mint sSQT for user's Staked SQT, we implement an ERC20 Token called vSQT, disable it's storage and transfer functionality. Overwrite it's `balanceOf` function to return the sum of user's SQT balance and staked SQT value.
```
contract SQToken is ERC20 {
         ......
         function balanceOf(address account) public view virtual override returns (uint256) {
                  return IERC20(settings.getSQToken()).balanceOf(account) + IStaking(settings.getStaking()).delegation(account);
         }
         ......     
}
```

**Comment by Jianzhuo** [comment]
### token-based voting contract
Instead of using [Snapshot](https://docs.snapshot.org/), we also can implement a [Governance contract](https://medium.com/upstate-interactive/how-to-build-a-distributed-token-based-voting-app-on-ethereum-8be26ba36d10) to handle the distributed voting.
```
contract Governance {
         // Map a proposal ID to a specific proposal
         mapping(uint => Proposal) public proposals;
         // Map a proposal ID to a voter's address and their vote
         mapping(uint => mapping(address => bool)) public voted;
         // Determine if the user is blocked from voting
         mapping (address => uint) public blocked;

         struct Proposal {
                  uint votesReceived;
                  bool passed;
                  address submitter;
                  uint votingDeadline;
         }

         /// Allows a token holder to submit a proposal to vote on
         function submitProposal(){...}
  
         /// Adds a new proposal to the proposal mapping
         function addProposal(){...}

         /// Allows token holders to submit their votes in favor of a specific proposalID
         function submitVote(){...}

         /// Sets when a particular vote will end
         function endVote(){...}

         ///Determines whether or not a particular vote has passed or failed
         function voteSuccessOrFail(){...}
}

```

**Comment by Jianzhuo** [comment]
### Prevent voter fraud
For instance, a constituent from voting on a proposal and then sending their tokens to a different wallet and re-voting with the same tokens that they’ve already voted with. As a token shouldn’t be double-spent, a token shouldn’t vote twice.

#### Solution 1 -- Tokens with a history
The EVM does not allow smart contracts to read the state of past blocks. Therefore the token must keep track of its balances in time. We can lent the basic concepts of checkpoints from GiveEth’s [MiniMe Token](https://github.com/Giveth/minime/blob/master/contracts/MiniMeToken.sol) that presents us with a function where the historical balance of the token can be retrieved by performing a binary search over an array of checkpoints [MiniMe]:
```
    /// `Checkpoint` is the structure that attaches a block number to a
    struct  Checkpoint {
        // `fromBlock` is the block number that the value was generated from
        uint128 fromBlock;
        // `value` is the amount of tokens at a specific block number
        uint128 value;
    }

    // `balances` is the map that tracks the balance of each address, in this
    //  contract when the balance changes the block number that the change
    //  occurred is also included in the map
    mapping (address => Checkpoint[]) balances;

    /// @dev This is the actual transfer function in the token contract, it can
    ///  only be called by other functions in this contract.
    function doTransfer(address _from, address _to, uint _amount) internal {...}

    /// @dev `getValueAt` retrieves the number of tokens at a given block number    
    /// @param checkpoints The history of values being queried    
    /// @param _block The block number to retrieve the value at    
    /// @return The number of tokens being queried    
    function getValueAt(Checkpoint[] storage checkpoints, uint _block) constant internal returns (uint) {...}
```

#### Solution 2 -- Escrowing voted tokens
We’re using this mapping to determine whether or not a particular constituent is blocked from voting. We block a constituent from voting if they’ve already voted or submitted a proposal, and the proposal’s votingDeadline has not yet elapsed. If a users is blocked they are unable to transfer their tokens until the votingDeadline has elapsed.

**A shortcoming to this approach is that it disincentives voting as constituents will be unable to transfer their tokens if they’re in a blocked state.**

**Comment by ianhe8x** [comment]
We decide to use snapshot.
